// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: querypro/plugin/v1/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ConnectResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesRequest) Reset() {
	*x = ResourcesRequest{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesRequest) ProtoMessage() {}

func (x *ResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesRequest.ProtoReflect.Descriptor instead.
func (*ResourcesRequest) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ResourcesRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type ResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesResponse) Reset() {
	*x = ResourcesResponse{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcesResponse) ProtoMessage() {}

func (x *ResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcesResponse.ProtoReflect.Descriptor instead.
func (*ResourcesResponse) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Danger        bool                   `protobuf:"varint,3,opt,name=danger,proto3" json:"danger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Action) GetDanger() bool {
	if x != nil {
		return x.Danger
	}
	return false
}

type ActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsRequest) Reset() {
	*x = ActionsRequest{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsRequest) ProtoMessage() {}

func (x *ActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsRequest.ProtoReflect.Descriptor instead.
func (*ActionsRequest) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ActionsRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ActionsRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsResponse) Reset() {
	*x = ActionsResponse{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsResponse) ProtoMessage() {}

func (x *ActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsResponse.ProtoReflect.Descriptor instead.
func (*ActionsResponse) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Row) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Table) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Live struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Live) Reset() {
	*x = Live{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live) ProtoMessage() {}

func (x *Live) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live.ProtoReflect.Descriptor instead.
func (*Live) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*QueryResponse_Table
	//	*QueryResponse_Text
	//	*QueryResponse_Live
	//	*QueryResponse_Line
	Event         isQueryResponse_Event `protobuf_oneof:"event"`
	Summary       string                `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_querypro_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_querypro_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResponse) GetEvent() isQueryResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *QueryResponse) GetTable() *Table {
	if x != nil {
		if x, ok := x.Event.(*QueryResponse_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *QueryResponse) GetText() string {
	if x != nil {
		if x, ok := x.Event.(*QueryResponse_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *QueryResponse) GetLive() *Live {
	if x != nil {
		if x, ok := x.Event.(*QueryResponse_Live); ok {
			return x.Live
		}
	}
	return nil
}

func (x *QueryResponse) GetLine() string {
	if x != nil {
		if x, ok := x.Event.(*QueryResponse_Line); ok {
			return x.Line
		}
	}
	return ""
}

func (x *QueryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type isQueryResponse_Event interface {
	isQueryResponse_Event()
}

type QueryResponse_Table struct {
	Table *Table `protobuf:"bytes,1,opt,name=table,proto3,oneof"`
}

type QueryResponse_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type QueryResponse_Live struct {
	Live *Live `protobuf:"bytes,3,opt,name=live,proto3,oneof"`
}

type QueryResponse_Line struct {
	Line string `protobuf:"bytes,4,opt,name=line,proto3,oneof"`
}

func (*QueryResponse_Table) isQueryResponse_Event() {}

func (*QueryResponse_Text) isQueryResponse_Event() {}

func (*QueryResponse_Live) isQueryResponse_Event() {}

func (*QueryResponse_Line) isQueryResponse_Event() {}

var File_querypro_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_querypro_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1fquerypro/plugin/v1/plugin.proto\x12\x12querypro.plugin.v1\"\"\n" +
	"\x0eConnectRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"C\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\"-\n" +
	"\x11DisconnectRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"\x14\n" +
	"\x12DisconnectResponse\"2\n" +
	"\bResource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x10ResourcesRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"O\n" +
	"\x11ResourcesResponse\x12:\n" +
	"\tresources\x18\x01 \x03(\v2\x1c.querypro.plugin.v1.ResourceR\tresources\"J\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06danger\x18\x03 \x01(\bR\x06danger\"d\n" +
	"\x0eActionsRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x128\n" +
	"\bresource\x18\x02 \x01(\v2\x1c.querypro.plugin.v1.ResourceR\bresource\"G\n" +
	"\x0fActionsResponse\x124\n" +
	"\aactions\x18\x01 \x03(\v2\x1a.querypro.plugin.v1.ActionR\aactions\">\n" +
	"\fQueryRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"\x1b\n" +
	"\x03Row\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"N\n" +
	"\x05Table\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.querypro.plugin.v1.RowR\x04rows\"\x06\n" +
	"\x04Live\"\xc1\x01\n" +
	"\rQueryResponse\x121\n" +
	"\x05table\x18\x01 \x01(\v2\x19.querypro.plugin.v1.TableH\x00R\x05table\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12.\n" +
	"\x04live\x18\x03 \x01(\v2\x18.querypro.plugin.v1.LiveH\x00R\x04live\x12\x14\n" +
	"\x04line\x18\x04 \x01(\tH\x00R\x04line\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummaryB\a\n" +
	"\x05event2\xbe\x03\n" +
	"\rPluginService\x12R\n" +
	"\aConnect\x12\".querypro.plugin.v1.ConnectRequest\x1a#.querypro.plugin.v1.ConnectResponse\x12[\n" +
	"\n" +
	"Disconnect\x12%.querypro.plugin.v1.DisconnectRequest\x1a&.querypro.plugin.v1.DisconnectResponse\x12X\n" +
	"\tResources\x12$.querypro.plugin.v1.ResourcesRequest\x1a%.querypro.plugin.v1.ResourcesResponse\x12R\n" +
	"\aActions\x12\".querypro.plugin.v1.ActionsRequest\x1a#.querypro.plugin.v1.ActionsResponse\x12N\n" +
	"\x05Query\x12 .querypro.plugin.v1.QueryRequest\x1a!.querypro.plugin.v1.QueryResponse0\x01B\x1dZ\x1bquerypro/internal/plugin/pbb\x06proto3"

var (
	file_querypro_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_querypro_plugin_v1_plugin_proto_rawDescData []byte
)

func file_querypro_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_querypro_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_querypro_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_querypro_plugin_v1_plugin_proto_rawDesc), len(file_querypro_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_querypro_plugin_v1_plugin_proto_rawDescData
}

var file_querypro_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_querypro_plugin_v1_plugin_proto_goTypes = []any{
	(*ConnectRequest)(nil),     // 0: querypro.plugin.v1.ConnectRequest
	(*ConnectResponse)(nil),    // 1: querypro.plugin.v1.ConnectResponse
	(*DisconnectRequest)(nil),  // 2: querypro.plugin.v1.DisconnectRequest
	(*DisconnectResponse)(nil), // 3: querypro.plugin.v1.DisconnectResponse
	(*Resource)(nil),           // 4: querypro.plugin.v1.Resource
	(*ResourcesRequest)(nil),   // 5: querypro.plugin.v1.ResourcesRequest
	(*ResourcesResponse)(nil),  // 6: querypro.plugin.v1.ResourcesResponse
	(*Action)(nil),             // 7: querypro.plugin.v1.Action
	(*ActionsRequest)(nil),     // 8: querypro.plugin.v1.ActionsRequest
	(*ActionsResponse)(nil),    // 9: querypro.plugin.v1.ActionsResponse
	(*QueryRequest)(nil),       // 10: querypro.plugin.v1.QueryRequest
	(*Row)(nil),                // 11: querypro.plugin.v1.Row
	(*Table)(nil),              // 12: querypro.plugin.v1.Table
	(*Live)(nil),               // 13: querypro.plugin.v1.Live
	(*QueryResponse)(nil),      // 14: querypro.plugin.v1.QueryResponse
}
var file_querypro_plugin_v1_plugin_proto_depIdxs = []int32{
	4,  // 0: querypro.plugin.v1.ResourcesResponse.resources:type_name -> querypro.plugin.v1.Resource
	4,  // 1: querypro.plugin.v1.ActionsRequest.resource:type_name -> querypro.plugin.v1.Resource
	7,  // 2: querypro.plugin.v1.ActionsResponse.actions:type_name -> querypro.plugin.v1.Action
	11, // 3: querypro.plugin.v1.Table.rows:type_name -> querypro.plugin.v1.Row
	12, // 4: querypro.plugin.v1.QueryResponse.table:type_name -> querypro.plugin.v1.Table
	13, // 5: querypro.plugin.v1.QueryResponse.live:type_name -> querypro.plugin.v1.Live
	0,  // 6: querypro.plugin.v1.PluginService.Connect:input_type -> querypro.plugin.v1.ConnectRequest
	2,  // 7: querypro.plugin.v1.PluginService.Disconnect:input_type -> querypro.plugin.v1.DisconnectRequest
	5,  // 8: querypro.plugin.v1.PluginService.Resources:input_type -> querypro.plugin.v1.ResourcesRequest
	8,  // 9: querypro.plugin.v1.PluginService.Actions:input_type -> querypro.plugin.v1.ActionsRequest
	10, // 10: querypro.plugin.v1.PluginService.Query:input_type -> querypro.plugin.v1.QueryRequest
	1,  // 11: querypro.plugin.v1.PluginService.Connect:output_type -> querypro.plugin.v1.ConnectResponse
	3,  // 12: querypro.plugin.v1.PluginService.Disconnect:output_type -> querypro.plugin.v1.DisconnectResponse
	6,  // 13: querypro.plugin.v1.PluginService.Resources:output_type -> querypro.plugin.v1.ResourcesResponse
	9,  // 14: querypro.plugin.v1.PluginService.Actions:output_type -> querypro.plugin.v1.ActionsResponse
	14, // 15: querypro.plugin.v1.PluginService.Query:output_type -> querypro.plugin.v1.QueryResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_querypro_plugin_v1_plugin_proto_init() }
func file_querypro_plugin_v1_plugin_proto_init() {
	if File_querypro_plugin_v1_plugin_proto != nil {
		return
	}
	file_querypro_plugin_v1_plugin_proto_msgTypes[14].OneofWrappers = []any{
		(*QueryResponse_Table)(nil),
		(*QueryResponse_Text)(nil),
		(*QueryResponse_Live)(nil),
		(*QueryResponse_Line)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_querypro_plugin_v1_plugin_proto_rawDesc), len(file_querypro_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_querypro_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_querypro_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_querypro_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_querypro_plugin_v1_plugin_proto = out.File
	file_querypro_plugin_v1_plugin_proto_goTypes = nil
	file_querypro_plugin_v1_plugin_proto_depIdxs = nil
}
